#!/bin/bash

THEMES_DIR="$HOME/.config/waybar/themes"

# Get a list of themes and their color palettes
theme_list=()
while IFS= read -r -d '' theme; do
    theme_name=$(basename "$theme")
    while IFS= read -r -d '' palette; do
        palette_name=$(basename "$palette")
        theme_list+=("$theme_name/$palette_name")
    done < <(find "$theme" -mindepth 1 -maxdepth 1 -type d -print0)
done < <(find "$THEMES_DIR" -mindepth 1 -maxdepth 1 -type d -print0)

# Use Rofi to select a theme and palette
selected=$(printf "%s\n" "${theme_list[@]}" | rofi -dmenu -i -p "Select Waybar Theme")

# If a selection is made, update the Waybar configuration
if [[ -n "$selected" ]]; then
    theme=$(echo "$selected" | cut -d '/' -f 1)
    palette=$(echo "$selected" | cut -d '/' -f 2)

    rm -f "$HOME/.config/waybar/config.jsonc" "$HOME/.config/waybar/style.css"

    cp -r "$THEMES_DIR/$theme/$palette/config.jsonc" "$HOME/.config/waybar/config.jsonc"
    cp -r "$THEMES_DIR/$theme/$palette/style.css" "$HOME/.config/waybar/style.css"

    killall waybar
    waybar &
fi
