#!/bin/sh

SCRIPTS="$HOME/.config/river/scripts"

riverctl map normal Super Return spawn foot
riverctl map normal Super R spawn "fuzzel --config=/home/ray/.config/fuzzel/river.ini"
riverctl map normal Super B spawn firefox 
riverctl map normal Super E spawn thunar 
riverctl map normal Super+Shift R spawn "$SCRIPTS/randwall"
riverctl map normal Super+Shift S spawn "$SCRIPTS/screenshot"
riverctl map normal Super+Shift C spawn "$SCRIPTS/fuzzel-calc"
riverctl map normal Super+Shift B spawn "$SCRIPTS/get-bookmark"
riverctl map normal Super+Shift Y spawn "wl-color-picker clipboard"
riverctl map normal Super+Control G spawn "$SCRIPTS/toggle-gammastep" 
riverctl map normal Super+Control I spawn "$SCRIPTS/toggle-swayidle" 
riverctl map normal Super+Control R spawn "$SCRIPTS/record-screen"
riverctl map normal Super+Control B spawn "$SCRIPTS/toggle-bar"
riverctl map normal Super Q close
riverctl map normal Super+Control E exit

# for the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Mod+H and Mod+L to decrease/increase the main ratio of rivercarro
riverctl map normal Super H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivercarro "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivercarro
riverctl map normal Super+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivercarro "main-count -1"

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal Super Right send-layout-cmd rivercarro "main-location right"
riverctl map normal Super Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivercarro "main-location left"
riverctl map normal Super M     send-layout-cmd rivercarro "main-location monocle"
# riverctl map normal Super G		send-layout-cmd riverdeck "main-location grid"
# riverctl map normal Super D		send-layout-cmd riverdeck "main-location deck"

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output DP-1 
riverctl map normal Super Comma focus-output DP-3 

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view
# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view
# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float
riverctl input pointer-5426-152-Razer_Razer_DeathAdder_Essential pointer-accel -0.5

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# SCRATCHPADS 
# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad with Super+P
riverctl map normal Super P toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map normal Super+Shift P set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}


# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    # riverctl map $mode None XF86Eject spawn 'eject -T'

    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done


# keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
# riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
# riverctl rule-add -app-id "bar" csd

riverctl rule-add ssd
riverctl set-cursor-warp on-focus-change
riverctl focus-follows-cursor normal
riverctl allow-tearing enabled

riverctl background-color 0x111111
#riverctl border-color-focused 0x4488ffff
riverctl border-color-focused 0x941729ff
riverctl border-color-unfocused 0x444444cc
riverctl border-color-urgent 0xf54927cc
riverctl border-width 1 

riverctl default-layout rivercarro 
rivercarro -no-smart-gaps -outer-gaps 6 -main-ratio 0.5 -per-tag &

# necessary programs
riverctl spawn dunst 
riverctl spawn kanshi
riverctl spawn "~/.config/river/scripts/riverstatus | dam"

# custom setup for my system
riverctl spawn "$SCRIPTS/randwall"
riverctl spawn "$SCRIPTS/display-align"
wlr-randr --output DP-3 --mode 2560x1440@239.970001 --pos 0,0 --output DP-1 --mode 1920x1080@144.001007 --pos 2560,0
#riverctl xcursor-theme WhiteSur-cursors 

# for screensharing portal to work w/ systemd
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal

# idle management
swayidle -w \
  timeout 900 'wlopm --off "*"' \
  resume       'sleep 1 && wlopm --on "*"' \
  before-sleep 'wlopm --off "*"' \
  timeout 1800 'systemctl suspend' & disown
