#!/bin/sh

wlr-randr --output DP-3 --mode 2560x1440@239.970001 --pos 0,0 --output DP-1 --mode 1920x1080@144.001007 --pos 2560,0
xrandr --output DP-3 --primary  # for games to run at 1440p because xwayland
