#!/bin/sh

while true; do
	cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}')
	memory="$(free -h | sed -n "2s/\([^ ]* *\)\{2\}\([^ ]*\).*/\2/p")"
	current_time=$(date +"%Y-%m-%d %I:%M %p")
	cat <<< "π $cpu_usage | μ $memory | τ $current_time"
	sleep 2 
done
