#!/bin/sh

if pgrep -x gammastep >/dev/null; then
    pkill gammastep \
      && notify-send -t 4000 'Nightlight disabled'
else
    gammastep & disown \
      && notify-send -t 4000 'Nightlight enabled'
fi
