# colors for foot terminal
# You can use this template by adding the following to wallust.toml:
# foot = { template = "foot.ini", target = "~/.config/foot/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/foot/colors.ini


[colors]
background=101011
foreground=D5DDE1

# Normal/regular colors (color palette 0-7)
regular0=393939  # black
regular1=101012  # red
regular2=224141  # green
regular3=414258  # yellow
regular4=4D6F93  # blue
regular5=65726B  # magenta
regular6=879DA9  # cyan
regular7=BAC6CC  # white

# Bright colors (color palette 8-15)
bright0=838A8E   # bright black
bright1=101012   # bright red
bright2=224141   # bright green
bright3=414258   # bright yellow
bright4=4D6F93   # bright blue
bright5=65726B   # bright magenta
bright6=879DA9   # bright cyan
bright7=BAC6CC   # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>

